s3://my-iceberg-lake/iceberg/db_name/table_name/data/...
s3://my-iceberg-lake/iceberg/db_name/table_name/metadata/...
s3://my-iceberg-lake/iceberg/db_name/table_name/snapshots/...
s3://my-iceberg-lake/iceberg/db_name/table_name/checkpoints/